# file: roles/httpd/tasks/configure.yml

- name: Change default apache vhost
  template: src=default.tpl dest=/etc/httpd/conf.d/000-default.conf

- name: Set global ServerName for apache config
  lineinfile: dest=/etc/httpd/conf/httpd.conf line="ServerName localhost"

- name: SELinux to enforcing
  command: /sbin/setenforce 0
  notify:
    - restart httpd

- name: Ensure Apache running
  service: name=httpd state=started enabled=yes
  
- local_action: stat path=/usr/lib64/php/modules/xdebug.so
  register: xmodule
    
- name: build xdeubg module
  command: "sudo pecl install xdebug-2.2.7"
  when: not xmodule.stat.exists
    
- name: Add xdebug config to php.ini
  blockinfile:
    dest: /etc/php.ini
    block: |
        [xdebug]
        zend_extension=/usr/lib64/php/modules/xdebug.so
        xdebug.remote_enable=1
        xdebug.remote_connect_back=1
        xdebug.remote_port=9000
        xdebug.idekey=phpstorm
        xdebug.remote_autostart=1
        xdebug.extended_info=1 
    marker: ";; ansible managed xdebug setup"

- name: restart web server
  service:
    name: httpd
    state: restarted
      